export const MIN_CHANGE_DELAY = 1000;
export const MAX_CHANGE_DELAY = 2500;

export const DELAY_CONTRAST_THRESHOLD = 0.9;
export const SHORT_DELAY_CONTRAST = 3;
export const LONG_DELAY_CONTRAST = 2;

export const ORB_MIN_SIZE_MULTIPLIER = 0.3;
export const ORB_MAX_SIZE_MULTIPLIER = 1.0;

export const LOOP_ITERATION_DELAY = MAX_CHANGE_DELAY;

export const MAX_ANIMATION_TIME = 1000;